apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- department-deployment.yaml
- organization-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml

namespace: iso

images:
- name: department-image
  newName: harbor.tanzu.be/library/iso-department-service
  newTag: dfa3131f548f21ad610bfd269263ba42561fdf13
- name: organization-image
  newName: harbor.tanzu.be/library/iso-organization-service
  newTag: dfa3131f548f21ad610bfd269263ba42561fdf13
