apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- department-deployment.yaml
- organization-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml

namespace: iso
images:
- name: organization-image
  newName: harbor.tanzu.be/library/iso-organization-service
  newTag: b59.20211012.112258

- name: department-image
  newName: harbor.tanzu.be/library/iso-department-service
  newTag: b60.20211012.112300
