apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- department-deployment.yaml
- organization-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml

namespace: iso

images:
- name: department-image
  newName: harbor.services.e2e.jg-aws.com/tkg-demo/iso-department-service
  newTag: b1.20211019.001407
- name: organization-image
  newName: harbor.services.e2e.jg-aws.com/tkg-demo/iso-organization-service
  newTag: b1.20211019.001413