apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- employee-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml
- mongodb-deployment.yaml

namespace: iso

images:
- digest: sha256:f550a9ade62955c61aba08ec165986db87584fb058843533d439bbd5a045dbe0
  name: employee-image
  newName: harbor.services.demo.jg-aws.com/tkg-demo/iso-employee-service
